apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-api
  labels:
    app: synergychat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      containers:
      - image: docker.io/bootdotdev/synergychat-api:latest
        name: synergychat-api
        env:
          - name: API_PORT
            valueFrom:
              configMapKeyRef:
                name: synergychat-api-configmap
                key: API_PORT
            CRAWLER_BASE_URL: http://crawler-service.crawler.svc.cluster.local
        volumeMounts:
        - name: synergychat-api-volume
          mountPath: /persist
      volumes:
      - name: synergychat-api-volume
        persistentVolumeClaim:
          claimName: synergychat-api-pvc